### ISSUE TITLE
Match history is lost after updating to 6.3.8

### ISSUE THREAD

**Issue by azkore** [mtgatool/mtgatool-desktop#64]
Basically, the same issue as #61, which was closed as a duplicate of #62. However, #62 is now marked as fixed, but the issue remains unchanged for me:

My match history is empty. When I downgrade to 6.2.13, the history is restored. To do this, I have to turn off the network connection to prevent the app from updating to the latest version. Is there a way to disable autoupdates?

Any workaround to keep the history while using the latest version of the tool would be greatly appreciated.

**Comment by riQQ** [comment]
In the latest version, if you click on the account name in the top right, do you get to choose between multiple accounts/  IDs?

**Comment by azkore** [comment]
A question: is there a way to edit the database using some cli tool? I could try to understand the db structure and update the fields to match the new version expectations manually.

**Comment by Manwe-777** [comment]
Since 2.6.13 I moved all db and connection related layers to a web worker, before that it was as simple as accessing the `toolDb` object within the window, but now thats one layer down in the web worker, which is currently still in development (im still moving pieces of the db to the worker), you can see how the db works here;
 [https://github.com/manwe-777/mtgatool-db](https://github.com/manwe-777/mtgatool-db)
 
Unfortunately there is no CLI for the db yet, however I can guide you trough the db , since its all just javascript it should be quite straightforward once you have mtgatool running (either from source code or the app, or even on the browser)

The user data is under the `""userids""` key, that returns your MTG arena user ids with a timestamp and mtgatool infers the latest one as the default. from there you can follow the methods used in [afterLogin.ts](https://github.com/mtgatool/mtgatool-desktop/blob/dev/tooldb-worker/afterLogin.ts) to have an idea of the keys and functions used to gather all users match data. I recommend you triying this in `6.2.13` running from source code to get an idea first, there its just as easy as using `window.toolDb` on the browser or console with `Alt + Shift + D`, on the web workers version all of that is hidden from console access.

Also please hit me up on Discord if you want ! im interested seeing what happened here since the latest version should show your user data properly.

**Comment by Manwe-777** [comment]
As per discussed on Discord, this issue was actually because the local db on the web worker could not see the old indexeddb outside the web worker, thus the data that was not synchronized with the server was simply missing and could not be synchronized again.

We managed to solve it connecting `v6.2.13` to the server via commands and force pushing the match data to the server using a loop like this;

```
// connect to server 
window.toolDb.network.connectTo({"host":"api.mtgatool.com","ssl":true,"name":"mtgatool-default-server","pubKey":"ccdde0f639db3ccb18ed2d48ed405323eac3ce86762923c1010796433e9a392dec3771400f524d4f0a466c0701cad99bbd8b509df3a467c8ca76fab7dc5504bb","signature":"b39f2b4e41605b8629fb583ff519162d12a45eb10c4aa10a42867624ba2ab18f4a2ed43884eefd95a17f48846385fe404d54fa731ea6d47d6ee8aecfefc3873a"})

// send all local matches data
const keys=await self.toolDb.queryKeys(`:${self.toolDb.user.pubKey}.matches-`)
for (key of keys) { 
    let match=key.split('.')[1];
    console.log(match);
    const data=await self.toolDb.getData(key)
    await window.toolDb.putData(match, data, true);
}
```

im closing this issue because its solved but I wanted to give some insight on how we solved it in case it comes back for someone else.
